//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloPalauta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huoneet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Huoneet()
        {
            this.TalonTila = new HashSet<TalonTila>();
        }
    
        public int HuoneID { get; set; }
        public string HuoneenNimi { get; set; }
        public string HuoneenLampotila { get; set; }
        public string HuoneenTavoiteLampotila { get; set; }
        public Nullable<System.DateTime> PVM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalonTila> TalonTila { get; set; }
    }
}
