//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloPalauta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saunat
    {
        public int SaunaID { get; set; }
        public string SaunanSijainti { get; set; }
        public Nullable<bool> SaunaPaalla { get; set; }
        public string SaunanLampotila { get; set; }
        public Nullable<System.DateTime> PVM { get; set; }
    }
}
