//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloPalauta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TalonEntities : DbContext
    {
        public TalonEntities()
            : base("name=TalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Huoneet> Huoneet { get; set; }
        public virtual DbSet<Saunat> Saunat { get; set; }
        public virtual DbSet<TalonTila> TalonTila { get; set; }
        public virtual DbSet<Valot> Valot { get; set; }
    }
}
