//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloPalauta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int ValoID { get; set; }
        public string ValonSijainti { get; set; }
        public Nullable<bool> ValoPaalla { get; set; }
        public string ValonMaara { get; set; }
        public Nullable<System.DateTime> PVM { get; set; }
    }
}
